In [3]:
import pandas as pd

In [4]:
pd.__version__

'0.25.1'

In [5]:
d= pd.read_html("https://coronavirus.politologue.com/coronavirus-maroc.MA")

In [6]:
type(d)

list

In [7]:
len(d)

1

In [8]:
df=d[0]
df

    Unnamed: 0_level_0 Unnamed: 1_level_0  Total                    Taux  \
                  Date               Pays    Cas Morts Guérisons % Décès
0           2020-06-21              Maroc  9 977   214     8 284   2,14%
1           2020-06-20              Maroc  9 839   213     8 223   2,16%
2           2020-06-19              Maroc  9 613   213     8 117   2,22%
3           2020-06-18              Maroc  9 074   213     8 041   2,35%
4           2020-06-17              Maroc  8 997   213     7 993   2,37%
..                 ...                ...    ...   ...       ...     ...
107         2020-03-06              Maroc      2     0         0   0,00%
108         2020-03-05              Maroc      2     0         0   0,00%
109         2020-03-04              Maroc      1     0         0   0,00%
110         2020-03-03              Maroc      1     0         0   0,00%
111         2020-03-02              Maroc      1     0         0   0,00%

                        Nouveaux par jour
    % Guérison % Malade               Cas Décès Guérisons
0       83,03%   14,82%               138     1        61
1       83,58%   14,26%               226     0       106
2       84,44%   13,35%               539     0        76
3       88,62%    9,04%                77     0        48
4       88,84%    8,79%                66     1        56
..         ...      ...               ...   ...       ...
107      0,00%  100,00%                 0     0         0
108      0,00%  100,00%                 1     0         0
109      0,00%  100,00%                 0     0         0
110      0,00%  100,00%                 0     0         0
111      0,00%  100,00%                 1     0         0

[112 rows x 11 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 11 columns):
(Unnamed: 0_level_0, Date)        112 non-null object
(Unnamed: 1_level_0, Pays)        112 non-null object
(Total, Cas)                      112 non-null object
(Total, Morts)                    112 non-null int64
(Total, Guérisons)                112 non-null object
(Taux, % Décès)                   112 non-null object
(Taux, % Guérison)                112 non-null object
(Taux, % Malade)                  112 non-null object
(Nouveaux par jour, Cas)          112 non-null int64
(Nouveaux par jour, Décès)        112 non-null int64
(Nouveaux par jour, Guérisons)    112 non-null int64
dtypes: int64(4), object(7)
memory usage: 9.8+ KB

In [10]:
####saving the table in csv file

In [11]:
df.to_csv('Morroco_covid19.csv')

In [12]:
###saving the data in excel

In [13]:
df.to_excel('Morroco_covid19.xlsx')

In [14]:
url="https://coronavirus.politologue.com/coronavirus-france.FR"

In [15]:
url1="https://coronavirus.politologue.com/coronavirus-france.FR"
f= pd.read_html(url1)
fr=f[0]
fr

    Unnamed: 0_level_0 Unnamed: 1_level_0    Total                      Taux  \
                  Date               Pays      Cas   Morts Guérisons % Décès
0           2020-06-21             France  198 278  29 640    74 372  14,95%
1           2020-06-20             France  197 994  29 633    74 312  14,97%
2           2020-06-19             France  197 353  29 617    74 117  15,01%
3           2020-06-18             France  196 542  29 603    73 887  15,06%
4           2020-06-17             France  196 075  29 575    73 667  15,08%
..                 ...                ...      ...     ...       ...     ...
145         2020-01-28             France        4       0         0   0,00%
146         2020-01-27             France        3       0         0   0,00%
147         2020-01-26             France        3       0         0   0,00%
148         2020-01-25             France        3       0         0   0,00%
149         2020-01-24             France        2       0         0   0,00%

                        Nouveaux par jour
    % Guérison % Malade               Cas Décès Guérisons
0       37,51%   47,54%              +284    +7       +60
1       37,53%   47,50%              +641   +16      +195
2       37,56%   47,44%              +811   +14      +230
3       37,59%   47,34%              +467   +28      +220
4       37,57%   47,35%              +458   +28      +332
..         ...      ...               ...   ...       ...
145      0,00%  100,00%                +1     0         0
146      0,00%  100,00%                 0     0         0
147      0,00%  100,00%                 0     0         0
148      0,00%  100,00%                +1     0         0
149      0,00%  100,00%                +2     0         0

[150 rows x 11 columns]

In [16]:
fr.to_excel('France_covid19.xlsx')
fr.to_csv('France_covid19.csv')

In [17]:
url2="https://coronavirus.politologue.com/coronavirus-italie.IT"
url3="https://coronavirus.politologue.com/coronavirus-chine.CN"
i= pd.read_html(url2)
it=i[0]
c= pd.read_html(url3)
ch=c[0]
it.to_excel('Italy_covid19.xlsx')
it.to_csv('Italy_covid19.csv')
ch.to_excel('China_covid19.xlsx')
ch.to_csv('China_covid19.csv')

In [18]:
#####Importing covid data for the world

In [19]:
url_w="https://coronavirus.politologue.com/"
w=pd.read_html(url_w)
world=w[0]
world

    Unnamed: 0_level_0         Unnamed: 1_level_0     Totaux           \
                  Date                       Pays        Cas    Décès
0           2020-06-21                 États-Unis  2 269 463  119 868
1           2020-06-21                     Brésil  1 032 913   49 976
2           2020-06-21                     Russie    583 879    8 101
3           2020-06-21                       Inde    410 451   13 254
4           2020-06-21                Royaume-Uni    305 803   42 717
..                 ...                        ...        ...      ...
182         2020-06-21                    Vatican         12        0
183         2020-06-21                 Seychelles         11        0
184         2020-06-21          Sahara Occidental          9        1
185         2020-06-21  Papouasie-Nouvelle-Guinée          8        0
186         2020-06-21                    Lesotho          4        0

                 Taux                       Nouveaux
    Guérisons % Décès % Guérisons % Malades      Cas Décès   Guéris
0     617 460   5,28%      27,21%    67,51%  +14 344   149        0
1     576 779   4,84%      55,84%    39,32%        0     0  -12 295
2     339 142   1,39%      58,08%    40,53%   +7 717   109   +5 118
3     227 728   3,23%      55,48%    41,29%      -10     0      -28
4       1 319  13,97%       0,43%    85,60%   +1 399    43     +176
..        ...     ...         ...       ...      ...   ...      ...
182        12   0,00%     100,00%     0,00%        0     0        0
183        11   0,00%     100,00%     0,00%        0     0        0
184         8  11,11%      88,89%     0,00%        0     0        0
185         8   0,00%     100,00%     0,00%        0     0        0
186         2   0,00%      50,00%    50,00%        0     0        0

[187 rows x 11 columns]

In [24]:
world.to_excel('world_covid19.xlsx')
world.to_csv('world_covid19.csv')

In [25]:
world_evolution=w[1]
world_evolution

    Unnamed: 0_level_0      Total                        Taux             \
                  Date        Cas    Morts  Guérisons % Décès % Guérison
0           2020-06-21  8 858 407  465 823  4 399 131   5,26%     49,66%
1           2020-06-20  8 798 685  464 530  4 381 925   5,28%     49,80%
2           2020-06-19  8 671 662  460 081  4 249 397   5,31%     49,00%
3           2020-06-18  8 495 411  454 048  4 158 663   5,34%     48,95%
4           2020-06-17  8 356 118  449 022  4 077 398   5,37%     48,80%
..                 ...        ...      ...        ...     ...        ...
147         2020-01-26      2 118       56         52   2,64%      2,46%
148         2020-01-25      1 438       42         39   2,92%      2,71%
149         2020-01-24        941       26         36   2,76%      3,83%
150         2020-01-23        653       18         30   2,76%      4,59%
151         2020-01-22        555       17         28   3,06%      5,05%

             Nouveaux par jour
    % Malade               Cas   Décès Guérisons
0     45,08%           +59 722  +1 293   +17 206
1     44,92%          +127 023  +4 449  +132 528
2     45,69%          +176 251  +6 033   +90 734
3     45,70%          +139 293  +5 026   +81 265
4     45,83%          +176 157  +5 274  +118 838
..       ...               ...     ...       ...
147   94,90%              +680     +14       +13
148   94,37%              +497     +16        +3
149   93,41%              +288      +8        +6
150   92,65%               +98      +1        +2
151   91,89%              +555     +17       +28

[152 rows x 10 columns]

In [26]:
world_evolution.to_excel('world_evolution_covid19.xlsx')
world_evolution.to_csv('world_evolution_covid19.csv')

In [6]:
import pandas as pd

In [12]:
f=pd.read_html("https://coronavirus.politologue.com/carte-de-france/")
fr=f[0]
fr

,Département,Hospitalisations,Réanimations,Décès,Retours au domicile
0,Paris (75),601,76,1740,5965
1,Val-de-Marne (94),672,22,1189,3963
2,Hauts-de-Seine (92),807,65,1073,4191
3,Seine-Saint-Denis (93),721,65,980,3568
4,Moselle (57),298,23,825,2324
...,...,...,...,...,...
96,Guyane (973),119,16,7,243
97,Tarn-et-Garonne (82),3,1,6,42
98,Ariège (09),1,1,2,33
99,Lozère (48),0,0,1,24
100,La Réunion (974),24,3,1,132

In [14]:
fr.to_excel("Covid19_france_Dep.xlsx")

In [1]:
import pandas as pd

In [2]:
df= pd.read_excel(r"C:\Users\Abdouuulbari\Desktop\ELITECH\Talend\DATA\China_covid19.xlsx")

In [4]:
df.to_csv(r"C:\Users\Abdouuulbari\Desktop\ELITECH\Talend\DATA\CSV\China_covid19.csv")

In [5]:
a= pd.read_excel(r"C:\Users\Abdouuulbari\Desktop\ELITECH\Talend\DATA\world_covid19.xlsx")
b= pd.read_excel(r"C:\Users\Abdouuulbari\Desktop\ELITECH\Talend\DATA\Morroco_covid19.xlsx")
c= pd.read_excel(r"C:\Users\Abdouuulbari\Desktop\ELITECH\Talend\DATA\Italy_covid19.xlsx")
d= pd.read_excel(r"C:\Users\Abdouuulbari\Desktop\ELITECH\Talend\DATA\France_covid19.xlsx")
e= pd.read_excel(r"C:\Users\Abdouuulbari\Desktop\ELITECH\Talend\DATA\Covid19_france_Dep_LatLong.xlsx")

In [6]:
a.to_csv(r"C:\Users\Abdouuulbari\Desktop\ELITECH\Talend\DATA\CSV\world_covid19.csv")
b.to_csv(r"C:\Users\Abdouuulbari\Desktop\ELITECH\Talend\DATA\CSV\Morroco_covid19.csv")
c.to_csv(r"C:\Users\Abdouuulbari\Desktop\ELITECH\Talend\DATA\CSV\Italy_covid19.csv")
d.to_csv(r"C:\Users\Abdouuulbari\Desktop\ELITECH\Talend\DATA\CSV\France_covid19.csv")
e.to_csv(r"C:\Users\Abdouuulbari\Desktop\ELITECH\Talend\DATA\CSV\Covid19_france_Dep_LatLong.csv")